import { z } from "zod";

import { IsoTimestampSchema, UuidSchema } from "./common";

/**
 * Stable machine ids for the 14 sections required by the assignment
 * (Bước 8 — "Tạo bản research spec"). Order here is the canonical display
 * order everywhere a `ResearchSpec` is rendered.
 */
export const SpecSectionIdSchema = z.enum([
  "PROBLEM_STATEMENT",
  "RESEARCH_QUESTIONS",
  "RELATED_WORK_MATRIX",
  "RESEARCH_GAP",
  "PROPOSED_APPROACH",
  "EXPECTED_CONTRIBUTIONS",
  "CLAIM_EVIDENCE_MATRIX",
  "EXPERIMENTAL_PROTOCOL",
  "BASELINES_AND_METRICS",
  "ABLATION_PLAN",
  "COMPUTE_BUDGET",
  "RISKS_AND_LIMITATIONS",
  "OPEN_ISSUES",
  "DECISION_HISTORY",
]);
export type SpecSectionId = z.infer<typeof SpecSectionIdSchema>;

export const SPEC_SECTION_ORDER = [
  "PROBLEM_STATEMENT",
  "RESEARCH_QUESTIONS",
  "RELATED_WORK_MATRIX",
  "RESEARCH_GAP",
  "PROPOSED_APPROACH",
  "EXPECTED_CONTRIBUTIONS",
  "CLAIM_EVIDENCE_MATRIX",
  "EXPERIMENTAL_PROTOCOL",
  "BASELINES_AND_METRICS",
  "ABLATION_PLAN",
  "COMPUTE_BUDGET",
  "RISKS_AND_LIMITATIONS",
  "OPEN_ISSUES",
  "DECISION_HISTORY",
] as const satisfies readonly SpecSectionId[];

/**
 * One assembled section. Content is deterministic prose/markdown composed
 * from already-validated project data — this module never calls an LLM.
 * Every upstream field it reads (interpretation, decomposition nodes,
 * literature, research-design, evidence) was already reviewed/generated by
 * an earlier, human-gated AI task; assembly only formats it (AI design
 * §17: this step adds no new PROPOSED content of its own).
 */
export const SpecSectionSchema = z.object({
  id: SpecSectionIdSchema,
  /** Human-readable numbered title, e.g. "1. Problem statement". */
  title: z.string().min(1).max(200),
  content: z.string().min(1).max(20_000),
  /** True when the underlying data does not exist yet (content explains what is missing, not invented). */
  isPlaceholder: z.boolean(),
});
export type SpecSection = z.infer<typeof SpecSectionSchema>;

export const ResearchSpecSchema = z.object({
  id: UuidSchema,
  projectId: UuidSchema,
  /** Monotonically increasing per project; Bước 10 creates a new version on each user revision. */
  version: z.number().int().positive(),
  sections: z.array(SpecSectionSchema).length(SPEC_SECTION_ORDER.length),
  createdAt: IsoTimestampSchema,
});
export type ResearchSpec = z.infer<typeof ResearchSpecSchema>;

export const GenerateResearchSpecInputSchema = z.object({
  projectId: UuidSchema,
});
export type GenerateResearchSpecInput = z.infer<
  typeof GenerateResearchSpecInputSchema
>;

export const GetResearchSpecInputSchema = z.object({
  projectId: UuidSchema,
});
export type GetResearchSpecInput = z.infer<typeof GetResearchSpecInputSchema>;

export const ListResearchSpecVersionsInputSchema = z.object({
  projectId: UuidSchema,
});
export type ListResearchSpecVersionsInput = z.infer<
  typeof ListResearchSpecVersionsInputSchema
>;

export const ListResearchSpecVersionsOutputSchema = z.object({
  items: z.array(ResearchSpecSchema),
});
export type ListResearchSpecVersionsOutput = z.infer<
  typeof ListResearchSpecVersionsOutputSchema
>;
